# Generated by Django 5.0.6 on 2024-07-06 08:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("actors", models.ManyToManyField(to="actors.actor")),
            ],
        ),
    ]
